namespace Apps.CustomMT.Constants;

public static class Languages
{
    public static readonly Dictionary<string, string> AvailableLanguages = new()
    {
        { "ab", "Abkhazian" },
        { "aa", "Afar" },
        { "af", "Afrikaans" },
        { "ak", "Akan" },
        { "sq", "Albanian" },
        { "am", "Amharic" },
        { "ar", "Arabic" },
        { "an", "Aragonese" },
        { "hy", "Armenian" },
        { "as", "Assamese" },
        { "av", "Avaric" },
        { "ae", "Avestan" },
        { "ay", "Aymara" },
        { "az", "Azerbaijani" },
        { "bm", "Bambara" },
        { "ba", "Bashkir" },
        { "eu", "Basque" },
        { "be", "Belarusian" },
        { "bn", "Bengali" },
        { "bi", "Bislama" },
        { "bs", "Bosnian" },
        { "br", "Breton" },
        { "bg", "Bulgarian" },
        { "my", "Burmese" },
        { "ca", "Catalan" },
        { "km", "Central Khmer" },
        { "ch", "Chamorro" },
        { "ce", "Chechen" },
        { "zh", "Chinese" },
//        { "none", "Chinese (Traditional)" },
        { "cv", "Chuvash" },
        { "kw", "Cornish" },
        { "co", "Corsican" },
        { "cr", "Cree" },
        { "hr", "Croatian" },
        { "cs", "Czech" },
        { "da", "Danish" },
        { "nl", "Dutch" },
        { "dz", "Dzongkha" },
        { "en", "English" },
       // { "none", "English (United Kingdom)" },
       // { "none", "English (United States)" },
        { "eo", "Esperanto" },
        { "et", "Estonian" },
        { "ee", "Ewe" },
        { "fo", "Faroese" },
        { "fj", "Fijian" },
        { "fi", "Finnish" },
        { "fr", "French" },
     //   { "none", "French (France)" },
        { "ff", "Fulah" },
        { "gd", "Gaelic" },
        { "gl", "Galician" },
        { "lg", "Ganda" },
        { "ka", "Georgian" },
        { "de", "German" },
        { "el", "Greek" },
        { "kl", "Greenlandic" },
        { "gn", "Guarani" },
        { "gu", "Gujarati" },
        { "ht", "Haitian" },
        { "ha", "Hausa" },
        { "he", "Hebrew" },
        { "hz", "Herero" },
        { "hi", "Hindi" },
        { "ho", "Hiri Motu" },
        { "hu", "Hungarian" },
        { "is", "Icelandic" },
        { "io", "Ido" },
        { "ig", "Igbo" },
        { "id", "Indonesian" },
        { "iu", "Inuktitut" },
        { "ik", "Inupiaq" },
        { "ga", "Irish" },
        { "it", "Italian" },
        { "ja", "Japanese" },
        { "jv", "Javanese" },
        { "kn", "Kannada" },
        { "kr", "Kanuri" },
        { "ks", "Kashmiri" },
        { "kk", "Kazakh" },
        { "rw", "Kinyarwanda" },
        { "kv", "Komi" },
        { "kg", "Kongo" },
        { "ko", "Korean" },
        { "ku", "Kurdish" },
        { "ky", "Kyrgyz" },
        { "lo", "Lao" },
        { "la", "Latin" },
        { "lv", "Latvian" },
        { "ln", "Lingala" },
        { "lt", "Lithuanian" },
        { "lu", "Luba-Katanga" },
        { "lb", "Luxembourgish" },
        { "mk", "Macedonian" },
        { "mg", "Malagasy" },
        { "ms", "Malay" },
        { "ml", "Malayalam" },
        { "dv", "Maldivian" },
        { "mt", "Maltese" },
        { "gv", "Manx" },
        { "mi", "Maori" },
        { "mr", "Marathi" },
        { "mh", "Marshallese" },
        { "mn", "Mongolian" },
        { "na", "Nauru" },
        { "nv", "Navaho" },
        { "ng", "Ndonga" },
        { "ne", "Nepali" },
        { "nd", "North Ndebele" },
        { "se", "Northern Sami" },
        { "nb", "Norwegian" },
        { "no", "Norwegian" },
        { "oc", "Occitan" },
        { "oj", "Ojibwa" },
        { "or", "Oriya" },
        { "om", "Oromo" },
        { "os", "Ossetian" },
        { "pi", "Pali" },
        { "fa", "Persian" },
        { "pl", "Polish" },
        { "pt", "Portuguese" },
     //   { "none", "Portuguese (Brazil)" },
        { "pa", "Punjabi" },
        { "ps", "Pushto" },
        { "qu", "Quechua" },
        { "ro", "Romanian" },
        { "rm", "Romansh" },
        { "rn", "Rundi" },
        { "ru", "Russian" },
        { "sm", "Samoan" },
        { "sg", "Sango" },
        { "sa", "Sanskrit" },
        { "sc", "Sardinian" },
        { "sr", "Serbian" },
        { "sn", "Shona" },
        { "ii", "Sichuan Yi" },
        { "sd", "Sindhi" },
        { "si", "Sinhalese" },
        { "sk", "Slovak" },
        { "sl", "Slovenian" },
        { "so", "Somali" },
        { "nr", "South Ndebele" },
        { "st", "Southern Sotho" },
        { "es", "Spanish" },
        { "su", "Sundanese" },
        { "sw", "Swahili" },
        { "ss", "Swati" },
        { "sv", "Swedish" },
        { "tl", "Tagalog" },
        { "ty", "Tahitian" },
        { "tg", "Tajik" },
        { "ta", "Tamil" },
        { "tt", "Tatar" },
        { "te", "Telugu" },
        { "th", "Thai" },
        { "bo", "Tibetan" },
        { "ti", "Tigrinya" },
        { "to", "Tonga" },
        { "ts", "Tsonga" },
        { "tn", "Tswana" },
        { "tr", "Turkish" },
        { "tk", "Turkmen" },
        { "tw", "Twi" },
        { "ug", "Uighur" },
        { "uk", "Ukrainian" },
        { "ur", "Urdu" },
        { "uz", "Uzbek" },
        { "ve", "Venda" },
        { "vi", "Vietnamese" },
        { "vo", "Volapük" },
        { "wa", "Walloon" },
        { "cy", "Welsh" },
        { "fy", "Western Frisian" },
        { "wo", "Wolof" },
        { "xh", "Xhosa" },
        { "yi", "Yiddish" },
        { "yo", "Yoruba" },
        { "za", "Zhuang" },
        { "zu", "Zulu" }
    };
}